### PR TITLE
fix marker issue

### LINKED ISSUE #31: Tilde not recognized as sound
@xrotwang @LinguList In some datasets, we have started using a tilde representing a floating nasality feature, corresponding to nasal consonants in other languages. However, this is not recognized by the `syllable_complexity` function from cltoolkit/features/phonology (line 419), crashing the lexibank 2.0 conversion. . What would be the best way to work around this issue?

### PR DESCRIPTION
**Pull request by FredericBlum**
Closes #31 

Adds an additional condition for iterating through syllables.

### CODE REVIEW

**Review by xrotwang — APPROVED** [review]

**Comment by xrotwang** [comment]
Maybe we should fix CI here as well, i.e., run tests on python >= 3.8 only

**Review by xrotwang — APPROVED** [review]

**Review by LinguList — CHANGES_REQUESTED** [review]
I think this approach does not address the issue at hand, as I mentioned in #31, which is: we have the tilde being recognized as marker in CLTS but as sound (a nasal) in LingPy. That means, the idx issue is due to the discrepancy here. We better address the issue by making sure the tilde is for now handled as a normal sound, until this is fixed from within of CLTS.

```python
from cltoolkit.features.phonology import syllable_complexity
from pyclts import CLTS
from lingpy.basictypes import lists
import collections
from cltoolkit.util import iter_syllables


def syllable_complexity(forms_with_sounds):
    """
    Compute the major syllabic patterns for a language.

    .. note::

       The computation follows the automated syllabification process described in
       List (2014) based on sonority. Based on this syllabification, we calculate
       the number of consonants preceding the syllable nucleus and those following
       it. For a given syllable, we store the form, the consonantal sounds, and
       the index of the syllable in the word. These values are returned in the
       form of two dictionaries, in which the number of sounds is the key.
    """

    preceding, following = collections.defaultdict(list), collections.defaultdict(list)
    for form in forms_with_sounds:
        idx = 0
        sounds_in_form = [s for s in form.sound_objects if (
            s.type != "marker" or s.obj.grapheme == '∼')]
        for i, syllable in enumerate(iter_syllables(form)):
            sounds, count = [], 0
            sounds_in_syllable = []
            for token in syllable:
                sounds_in_syllable += [sounds_in_form[idx]]
                idx += 1
            for sound in sounds_in_syllable:
                if (sound.type not in ['vowel', 'diphthong', 'tone', 'marker'] and \
                        'syllabic' not in sound.obj.featureset
                    ) or sound.obj.grapheme == '∼':
                    count += 1
                    sounds += [sound]
                else:
                    break
            preceding[count] += [(form, sounds, i)]
            sounds, count = [], 0
            for sound in sounds_in_syllable[::-1]:
                if sound.type not in ['vowel', 'diphthong']:
                    if sound.type not in ['tone', 'marker']:
                        count += 1
                        sounds += [sound]
                else:
                    break
            following[count] += [(form, sounds, i)]

    return preceding, following


class Sound:

    def __init__(self, sound):
        self.obj = sound
        self.type = sound.type

    def __repr__(self):
        return str(self.obj)
        

class FormWithSounds:

    def __init__(self, seq, ts):
        self.sounds = lists(seq)
        self.sound_objects = [Sound(ts[s]) for s in self.sounds]
        self.seq = seq

    def __iter__(self):
        return iter(self.sounds)
    
    def __repr__(self):
        return str(self.sounds)


forms = [
        "t a t a t",
        "t a t + t a t",
        "t a t + t a ∼ k"
        ]

ts = CLTS().bipa

fws = [FormWithSounds(f, ts) for f in forms]

p, f = syllable_complexity(fws)
```

This code fixes the small test case, it can be added to our test suite, and it addresses the problem by explicitly adding the tilde as a special case, which is causing the problem here.

**Comment by LinguList** [comment]
I added the full code, since in this script, you can easily see what happens, and how it is addressed.

1. we do not exclude the tilde from `sounds_in_form` (important!).
2. we do not treat the tilde, once it occurs within a syllable, as a marker, but add -- for now -- a special case where we check if the sound IS a tilde. 

The classes have just been created now to get the code running, since we have complex datatypes that are not easy to generate. But for the test at hand, it was useful.

**Comment by FredericBlum** [comment]
I have added the code as a new testfile, and run the code with the data to verify that it works. Should be mergeable now.

**Comment by FredericBlum** [comment]
Ok its not. I will check tomorrow how to fix the CLTS issue so that the test runs succesfully.

**Comment by LinguList** [comment]
Sure, the CLTS issue must point to a fixed CLTS path. We have fixtures for this. You can merge, and I handle from there?

**Comment by LinguList** [comment]
Actually, you have full access, even to the data model, if you check what we did in this test:

https://github.com/cldf/cltoolkit/blob/10c2692bd5370d042fc70494a0b948fea8e6a58d/tests/test_phonology.py#L19

So if you say `def test_features(clts):` then you add the code, it should do what you want, you have then loaded the internal CLTS that we added in the tests.

**Comment by LinguList** [comment]
It costs me always to understand this, but it seems to then really use the namespace defined in `conftest.py`, so `clts` means the variable `clts` defined here:

https://github.com/cldf/cltoolkit/blob/10c2692bd5370d042fc70494a0b948fea8e6a58d/tests/conftest.py#L20

**Comment by LinguList** [comment]
Just found this reference, @FredericBlum: https://docs.pytest.org/en/stable/reference/fixtures.html

**Comment by FredericBlum** [comment]
Took me some time to write the correct assert-statements for getting the coverage back up to 100%, but everything should be working now. The clts-integration through fixtures worked nicely though.

**Comment by LinguList** [comment]
Super :-)

**Pull request merged**
